# MotherDuck credentials for Streamlit Cloud deployment
# This file is gitignored - do not commit!

MOTHERDUCK_TOKEN = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFyc2FsYW4ubm9vcmFma2FuQGdldGJydWluLmNvbSIsIm1kUmVnaW9uIjoiYXdzLWV1LWNlbnRyYWwtMSIsInNlc3Npb24iOiJhcnNhbGFuLm5vb3JhZmthbi5nZXRicnVpbi5jb20iLCJwYXQiOiJ4cDYzTmhtbDk0UW1qSDJFbERWNm5aYWVON3JodGNhakpucGRWSDl6SjVBIiwidXNlcklkIjoiMGNlNTYzMTctYzM1Yy00YjljLWIyMzktYTFiNjYyZmJjNWY2IiwiaXNzIjoibWRfcGF0IiwicmVhZE9ubHkiOmZhbHNlLCJ0b2tlblR5cGUiOiJyZWFkX3dyaXRlIiwiaWF0IjoxNzY5MDk1NjQzfQ.QHDDMiJscvpKw_u6tm8vfVskkQMSnwxcUzc783trpXI"
